name: kolach

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - pip
  - git
  - diamond
  - mmseqs2
  - hmmer
  - snakemake-minimal=9
  - pytorch
  - pandas
  - tqdm
  - pip:
      - git+https://github.com/eggnogdb/eggnog-mapper.git@b3757a6d226047527a729546e58ff530d76a5d7d
      - git+https://github.com/zhaoxi120/deepkoala.git
      - -e .
