[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "kolach"
version = "0.0.0"
description = "Assign KEGG Orthology identifiers to proteins."
requires-python = ">=3.11"

[project.scripts]
kolach = "kolach.cli:main"

[tool.setuptools.packages.find]
where = ["src"]